// Generated by CoffeeScript 1.10.0
(function() {
  module.exports.doesTemplateReferenceIAM = function(compiledTemplate) {
    var key, ref, resource, template;
    template = JSON.parse(compiledTemplate);
    ref = template.Resources;
    for (key in ref) {
      resource = ref[key];
      if (resource.Type.match('AWS::IAM::.*')) {
        return true;
      }
    }
    return false;
  };

}).call(this);
